import java.util.Random;
public class SentenceOMatic{

    public static void main(String[] args){
        Random randomNumber = new Random();


        String[] start = {"The"};
        String[] adjectives = {"tiny", "gigantic", "smooth", "rough", "bright", "dull", "screeching", "whispering", "fragrant", "putrid", "bumpy", "sleek", "chilly", "scorching", "bitter", "sweet", "clammy", "dry", "spiky", "soft", "bubbly", "still", "winding", "straight", "drab", "vibrant", "melancholy", "joyful", "frantic", "calm", "fragile", "sturdy", "delicate", "clumsy", "enormous", "microscopic", "abundant", "scarce", "pungent", "odorless", "deafening", "silent", "glossy", "matte", "sour", "flavorful", "jagged", "round", "bumpy", "flat", "sparkling", "murky", "tangled", "organized", "monotonous", "diverse", "gloomy", "cheery", "frantic", "peaceful", "breakable", "unbreakable", "graceful", "awkward", "gigantic", "minuscule", "plentiful", "meager", "aromatic", "neutral", "deafening", "noiseless", "shiny", "dull", "tart", "savory", "uneven", "spherical", "dizzying", "steady", "complex", "simple", "dreary", "lively", "frantic", "serene", "vulnerable", "impenetrable", "elegant", "clumsy", "colossal", "minuscule", "copious", "sparse", "fragrant", "odorless", "earsplitting", "silent", "lustrous", "matte", "tart", "delicious", "jagged", "circular", "bumpy", "level", "glittering", "cloudy", "tangled", "organized", "monotonous", "varied", "gloomy", "cheerful", "hectic", "tranquil", "fragile", "indestructible", "refined", "awkward"};
        String[] noun ={"island", "city", "mountain", "forest", "star", "sun", "noise", "whisper", "flower", "garbage", "road", "car", "snowflake", "desert", "lemon", "candy", "sweat", "tear", "cactus", "pillow", "bubble", "wave", "path", "maze", "painting", "sculpture", "song", "melody", "book", "poem", "joke", "dream", "cloud", "rain", "ocean", "river", "spice", "herb", "sound", "silence", "diamond", "marble", "apple", "banana", "rock", "stone", "light", "shadow", "thread", "needle", "forest", "jungle", "lake", "stream", "festival", "celebration", "game", "competition", "tool", "machine", "building", "house", "history", "story", "memory", "thought", "idea", "belief", "emotion", "feeling", "eye", "ear", "nose", "tongue", "skin", "bone", "muscle", "hair", "planet", "universe", "animal", "plant"};
        String[] verb = {"dance", "sing", "shout", "whisper", "laugh", "cry", "run", "walk", "jump", "hop", "skip", "leap", "fly", "swim", "crawl", "climb", "dig", "push", "pull", "lift", "carry", "throw", "catch", "build", "break", "fix", "mend", "write", "draw", "paint", "sculpt", "play", "perform", "read", "learn", "teach", "speak", "listen", "think", "feel", "see", "hear", "smell", "taste", "touch", "explore", "discover", "imagine", "create", "solve", "help", "care", "love", "hate", "fear", "hope", "dream", "believe", "eat", "drink", "sleep", "wake", "dress", "undress", "bathe", "shower", "brush", "clean", "organize", "tidy", "relax", "rest", "work", "study", "travel", "explore", "adventure", "celebrate", "compete", "win", "lose", "change", "grow", "develop", "evolve", "adapt", "transform"};
        String[] nous = {"trip to the beach", "walk in the park", "fear of heights", "love for music", "search for treasure", "journey across the desert", "climb to the summit", "dive into the ocean", "respect for elders", "hunger for knowledge", "thirst for adventure", "craving for chocolate", "wait for the bus", "search for meaning", "hope for peace", "dream of flying", "preparation for the test", "payment for the service", "compensation for the loss", "gratitude for the help", "appetite for life", "dependence on technology", "obsession with cleanliness", "fascination with space", "aptitude for learning", "talent for painting", "passion for travel", "enthusiasm for sports", "desire for change", "yearning for home", "longing for the past", "anticipation of the future", "preparation for the exam", "anxiety about the presentation", "excitement for the vacation", "nervousness before the game", "relief after the storm", "sadness over the loss", "anger at the injustice", "guilt for the mistake", "curiosity about the unknown", "interest in history", "belief in God", "faith in humanity", "doubt about the truth", "suspicion of the stranger", "concern for the environment", "awareness of the problem", "understanding of the situation", "appreciation for the beauty", "admiration for the artist", "respect for the law", "sympathy for the victim", "empathy for the suffering", "compassion for the animals", "worry about the future", "stress at work", "boredom with the routine", "contentment with life", "agreement with the plan", "disagreement with the opinion", "argument over the issue", "discussion about the book", "debate on the topic", "explanation of the concept", "instruction on the task", "advice for the decision", "suggestion for improvement", "criticism of the work", "praise for the effort", "encouragement for the student", "warning about the danger", "reminder about the deadline", "invitation to the party", "gift for the birthday", "payment for the goods", "reward for the achievement", "punishment for the crime", "evidence for the claim", "proof of the theory", "excuse for the absence", "apology for the mistake", "explanation for the delay"};
        String[] adverb = {"slowly up the stairs", "quickly across the street", "here forever", "there for a while", "everywhere you look", "nowhere to be found", "always on time", "never late", "often in the mornings", "sometimes in the afternoons", "rarely at night", "very carefully", "incredibly fast", "extremely dangerous", "surprisingly easy", "too loud", "not very clear", "quite interesting", "rather boring", "kind of strange", "beautifully wrapped", "hopelessly lost", "desperately in need", "perfectly balanced", "absolutely necessary", "completely wrong", "partially finished", "brilliantly colored", "incredibly detailed", "dangerously close", "suspiciously quiet", "awkwardly phrased", "perfectly timed", "exquisitely prepared", "thoroughly confused", "utterly exhausted", "briefly mentioned", "vaguely remembered", "silently observed", "patiently waiting", "anxiously expecting", "confidently approaching", "hesitantly responding", "enthusiastically participating", "sadly leaving"};

    String randomSentence = start[0] + " " + adjectives[randomNumber.nextInt(adjectives.length)] + " " + noun[randomNumber.nextInt(noun.length)] + " " + verb[randomNumber.nextInt(verb.length)] + " " + nous[randomNumber.nextInt(nous.length)] + " " + adverb[randomNumber.nextInt(adverb.length)] + ".";

    System.out.println(randomSentence);
    }


}
